title: Samuel Meuli
baseURL: "https://samuelmeuli.com"
languageCode: en-us
theme: hugo-starter-theme

author:
  name: Samuel Meuli
  homepage: "https://samuelmeuli.com"

# Syntax highlighting
pygmentsStyle: friendly
pygmentsCodeFences: true

params:
  social:
    - name: github
      title: GitHub
      url: "https://github.com/samuelmeuli"
    - name: linkedin
      title: LinkedIn
      url: "https://www.linkedin.com/in/samuelmeuli"
    - name: product-hunt
      title: Product Hunt
      url: "https://producthunt.com/@samuelmeuli"
    - name: keybase
      title: Keybase
      url: "https://keybase.io/samuelmeuli"
    - name: rss
      title: RSS
      url: /index.xml
    - name: email
      title: Email
      email:
        username: me
        domain: samuelmeuli.com
